name: Build for Windows with Static Qt

on:
  push:
    branches:
      - ga-build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
           echo BUILD_DIR=%USERPROFILE%\build-dir >> $GITHUB_ENV
           echo QT_TARGET_DIR=%USERPROFILE%\qt-target >> $GITHUB_ENV
           echo VCPKG_ROOT=C:\vcpkg >> $GITHUB_ENV
           echo VCPKG_DEFAULT_TRIPLET=x64-windows-static >> $GITHUB_ENV

      - name: Update vcpkg to the latest revision
        run: |
             cd C:\vcpkg
             git pull
             .\bootstrap-vcpkg.bat

      - name: Build QT statically and build the app
        run: |
           call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath > vs_path.txt
           set /p VS_PATH=<vs_path.txt
           call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
           build-for-windows-with-static-qt.bat

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ env.BUILD_DIR }}\*.exe
          retention-days: 3