name: Build for macOS with Static Qt

on:
  push:
    branches: [ ga-build-macos ]
  workflow_dispatch:

env:
  SRC_DIR:   ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_TRIPLET: arm64-osx-release
  VCPKG_INSTALL_OPTIONS: "--clean-after-build"
  # ensure CMake will auto-invoke vcpkg manifest mode
  VCPKG_MANIFEST_MODE: "ON"

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: |
            brew update
            brew install automake autoconf libtool pkg-config autoconf-archive ninja

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: ${{ env.VCPKG_ROOT }}
          key: vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: vcpkg-

      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
          cd $VCPKG_ROOT
          ./bootstrap-vcpkg.sh

      - name: Copy vcpkg manifest
        run: |
          cp ${SRC_DIR}/build-configs/vcpkg-macos.json ${SRC_DIR}/vcpkg.json

      - name: Configure CMake (and install deps)
        run: |
          mkdir -p $BUILD_DIR && cd $BUILD_DIR
          cp ${SRC_DIR}/vcpkg.json .
          echo installing vcpkg packages
          vcpkg install $VCPKG_INSTALL_OPTIONS --triplet $VCPKG_TRIPLET
          echo installing vcpkg packages done
          echo configuring cmake
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=$VCPKG_TRIPLET \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_MANIFEST_MODE=ON \
            $SRC_DIR

      - name: Build & Package
        run: |
          cd $BUILD_DIR
          cmake --build . --config Release --target package
          cpack -G DragNDrop
